CREATE TABLE [dbo].[Friend]
(
	[Id]							UNIQUEIDENTIFIER	PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[UserId]						UNIQUEIDENTIFIER	NOT NULL ,
	[UserIdFriend]					UNIQUEIDENTIFIER	NOT NULL ,
	[Email]							NVARCHAR(50)		NOT NULL ,
	[EmailFriend]					NVARCHAR(100)		NOT NULL ,
	[Timestamp]						DATETIMEOFFSET		NOT NULL ,
	

	CONSTRAINT UC_EmailFriend UNIQUE (Email,EmailFriend),
	CONSTRAINT FK_User FOREIGN KEY ([UserId]) REFERENCES [dbo].[User]([Id]) ON DELETE CASCADE

)